planning_period: 0.01 # seconds
prediction_period: 0.05 # seconds
max_time_since_update: 2.0 # seconds
min_updates_to_confirm: 10

ball_speed1: 5.0 # metres per second
ball_speed2: 5.0 # metres per second
ball_speed_change_after: 480.0 # seconds (480s is 8min)

meas_filt:
  desired_dt: 0.5 # seconds
  buffer_length: 10
  covariance_inflation: 1.0 # how much to inflate the measurement covariance when choosing measurements
  loglikelihood_threshold: -5.0

lkf:
  min_init_points: 5
  max_speed_err: 3.5 # metre per second
  prediction_horizon: 2.0 # seconds
  prediction_step: 0.5 # seconds
  init_history_duration: 10.0 # seconds

  process_std:
    position: 5.0
    velocity: 8.0

  init_std:
    velocity: 8.0

ukf:
  min_radius: 1.5 # for estimated abs. curvatures larger than this, the UKF will be reset to sanitize the output
  prediction_horizon: 10.0 # seconds
  prediction_step: 0.5 # seconds
  init_history_duration: 10.0 # seconds

  process_std:
    position: 5.0
    yaw: 0.01
    curvature: 0.001

  init_std:
    yaw: 2.0
    speed: 1.0
    curvature: 2.0

lpf:
  rate: 25 # hertz
  cutoff_freq:
    curvature: 0.5 # hertz

z_bounds: # measurements outside these bounds will be ignored
  min: 0  # metres
  max: 20 # metres

rheiv:
  fitting_period: 1.0 # seconds
  min_points: 80
  max_points: 500
  visualization_size: 20 # metres
