planning_period: 0.01 # seconds
gating_distance: 20.0 # meters
max_time_since_update: 2.0 # seconds
min_updates_to_confirm: 10

ball_speed1: 8.0 # metres per second
ball_speed2: 5.0 # metres per second
ball_speed_change_after: 480.0 # seconds (480s is 8min)

ukf:
  prediction_horizon: 10.0 # seconds
  prediction_step: 0.5 # seconds
  prediction_period: 0.05 # seconds
  init_history_duration: 5 # seconds

process_std:
  position: 0.5
  yaw: 0.01
  speed: 0.0001
  curvature: 1.0

init_std:
  yaw: 2.0
  speed: 1.0
  curvature: 2.0

z_bounds: # measurements outside these bounds will be ignored
  min: 0  # metres
  max: 20 # metres

rheiv:
  fitting_period: 1.0 # seconds
  min_points: 100
  max_points: 500
  visualization_size: 5 # metres
