processing_period: 0.05 # seconds
prediction_period: 0.05 # seconds
max_time_since_update: 666.0 # seconds
min_updates_to_confirm: 8

ball_wire_length: 1.45 # metres
ball_speed1: 8.0 # metres per second
ball_speed2: 8.0 # metres per second
ball_speed_change_after: 480.0 # seconds (480s is 8min)

linefit:
  fitting_period: 1.0 # seconds
  threshold_distance: 1.5 # point must lie within this distance from the line to be considered inlier during fitting
  min_points: 10

circle:
  min_radius: 2.5 # fitted (RANSAC) or estimated (UKF) circles with radius smaller than this will be discarded
  max_radius: 20  # fitted circles with radius larger than this will be discarded
  fit_threshold_distance: 1.0 # point must lie within this distance from the circle to be considered inlier during fitting
  snap_threshold_distance: 3.0 # point must lie within this distance from the circle to be considered inlier during curvature snapping

lkf:
  use_acceleration: false # whether to include acceleration in the system model
  min_init_points: 5
  max_speed_err: 3.5 # metre per second
  prediction_horizon: 4.0 # seconds
  prediction_step: 0.4 # seconds
  init_history_duration: 20.0 # seconds

  process_std:
    position: 0.05
    velocity: 0.01
    acceleration: 0.5

  init_std:
    velocity: 0.5
    acceleration: 0.5

rheiv:
  fitting_period: 0.5 # seconds
  max_line_points_ratio: 0.5
  min_points: 10
  max_points: 80
  visualization_size: 20 # metres
  timeout: 1.0 # seconds
  line_threshold_distance: 1.0 # point must lie within this distance from the line to be considered inlier during fitting

bounds: # measurements outside these bounds will be ignored
  z:
    min: 5  # metres
    max: 15 # metres

ukf:
  prediction_horizon: 4.0 # seconds
  prediction_step: 0.4 # seconds
  init_history_duration: 20.0 # seconds

  meas_std:
    curvature_circ: 0.01
    curvature_line: 0.1

  process_std:
    position: 0.1
    yaw: 0.05
    curvature: 0.01

  init_std:
    yaw: 2.0
    curvature: 2.0
