planning_period: 0.01 # seconds
world_frame: "local_origin_stable"
gating_distance: 4.0 # meters
max_time_since_update: 2.0 # seconds
min_updates_to_confirm: 10

process_std:
  position: 0.5
  yaw: 0.01
  speed: 0.01
  curvature: 0.1
  quaternion: 0.00001

init_std:
  yaw: 2.0
  speed: 1.0
  curvature: 2.0
  quaternion: 0.6

z_bounds: # measurements outside these bounds will be ignored
  min: 5  # metres
  max: 10 # metres
