
# parameters of the pattern
pattern:
  radius:        15.5 # metres
  width:         85   # metres
  lin_cutoff:    5.0 # metres, how much of the radius will be cut-off in favour of the linear segment
  # parameters of transformation of the eight pattern
  rotation_ypr:  [0.0, 0.05, 0.05] # radians
  translation:   [3.0, 0.0, 12.5] # metres
  yaw: 0.0 # radians

# parameters of the sampling
sampling:
  speed:  8.0 # metres per second
  dt:     0.2 # seconds

plot_result: false # whether to plot the resulting trajectory using matplotlib
save_header: false # whether to save the column names on the first row of the csv file (to make it more human-readable)
